name: drmdabdusshakoor
description: "A professional portfolio and blog for Prof. Dr. Md. Abdus Shakoor."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#==============================================================================
# APP DEPENDENCIES
# These are the packages your app needs to run.
#==============================================================================
dependencies:
  flutter:
    sdk: flutter

  # Firebase Packages
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7

  # UI and Utility Packages
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3 # For saving like/view state on device
  url_launcher: ^6.3.0

#==============================================================================
# DEVELOPMENT DEPENDENCIES
# These packages are only used during development (e.g., for testing or code generation).
#==============================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # For generating app icons

#==============================================================================
# LAUNCHER ICON CONFIGURATION
# This section configures the 'flutter_launcher_icons' package.
#==============================================================================
flutter_launcher_icons:
  android: true
  ios: true
  # IMPORTANT: Make sure this path is correct.
  # The file 'prof-shakoor.png' must be inside the 'assets/icon/' folder.
  image_path: "assets/icon/prof-shakoor.png"
  min_sdk_android: 21 # Required for adaptive icons on Android
  web:
    generate: true # Generates icon for web version
  windows:
    generate: true # Generates icon for windows version

#==============================================================================
# FLUTTER-SPECIFIC CONFIGURATION
#==============================================================================
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # IMPORTANT: Make sure you have created these folders in your project.
  assets:
    - assets/images/
    - assets/icon/

